on: create
jobs:
  create-first-branches:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Create branches
        run: |
          git checkout -b staging && git push origin staging
          git checkout -b master && git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release-pull-request:
    if: ${{ contains(github.ref, 'refs/heads/release/') }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Extract version
        shell: bash
        run: |
          echo "::set-output name=version::${GITHUB_REF#refs/heads/release/v}"
        id: extract_version
      - run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Create pull request
        shell: bash
        run: |
          hub push
          hub pull-request -b main -m "Release ${{ steps.extract_version.outputs.version }}"
          hub pull-request -b staging -m "Release ${{ steps.extract_version.outputs.version }}"
