on: push
jobs:
  create-first-branches:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Create branches
        run: |
          git checkout -b staging && git push origin staging
          git checkout -b master && git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
